# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9df477aefe96d070d936e2fafc349a6625f4de37d75e13c34b3e75f44d7a5de7e4f60a9b55de2a3a35c1bb166e4ba88c8b1f202c5296ac78018221d84a1e1b9e
  github_key: ENV['GITHUB_KEY']
  github_secret: ENV['GITHUB_SECRET']

test:
  secret_key_base: 14685df00754346bd47e4c3945c4f88476c0eeeca13d2271f3a75c47a29aee8f06bf9e70f4ff32becc101e4fda4c95ce1b4e1ab944beac0b3d13c502b831aa65

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
